#!/bin/bash -l

#$ -P talbot-lab-data
#$ -j y

# Load modules and inputs
module load miniconda
conda activate qiime2-2020.2
source ../inputs.sh

# Single end if only FWD
if [ -z "$REV_FMT" ]
then
    PAIRED=false
else
    PAIRED=true
fi

### 1) CREATE QIIME2 ARTIFACT
echo CREATING QIIME ARTIFACT
python $SCRIPTSDIR/generate_artifact.py -i $INPUTDIR -f="$FWD_FMT" -r="$REV_FMT" -o $OUTPUTDIR
demux_artifact=$OUTPUTDIR/artifact.qza
echo QIIME ARTIFACT CREATED AT: $demux_artifact
echo

### 2) Trim primers
echo TRIMMING PRIMERS
trim_output=$OUTPUTDIR/trimmed.qza
if [ "$PAIRED" == "true" ]
then
    trim_setting="trim-paired"
    front_option="p-front-f"
    rev_option="p-front-r"
else
    trim_setting="trim-single"
    front_option="p-front"
    rev_option="p-anywhere"
fi

qiime cutadapt $trim_setting \
    --i-demultiplexed-sequences $demux_artifact \
    --$front_option $FWD_PRIMER \
    --$rev_option $REV_PRIMER \
    --p-error-rate 0.1 \
    --p-indels True \
    --p-times 2 \
    --p-overlap 3 \
    --p-match-read-wildcards True \
    --p-match-adapter-wildcards True \
    --p-minimum-length 50 \
    --p-cores $(nproc) \
    --verbose \
    --o-trimmed-sequences $trim_output