#!/bin/bash -l

#$ -P talbot-lab-data
#$ -j y

# Load modules and inputs
module load miniconda
conda activate qiime2-2020.2
source ../inputs.sh

# Single end if only FWD
if [ -z "$REV_FMT" ]
then
    PAIRED=false
else
    PAIRED=true
fi

# Show welcome
python $SCRIPTSDIR/welcome.py -i ../inputs.sh

### 1) CREATE QIIME2 ARTIFACT
echo CREATING QIIME ARTIFACT
cmd="python $SCRIPTSDIR/generate_artifact.py -i $INPUTDIR -f=$FWD_FMT -r=$REV_FMT -o $OUTPUTDIR"
echo $cmd
echo
eval $cmd


demux_artifact=$OUTPUTDIR/artifact.qza
echo Saved QIIME artifact to: $demux_artifact
echo

### 2) Trim primers
echo TRIMMING PRIMERS
trim_output=$OUTPUTDIR/trimmed.qza
if [ $PAIRED == "true" ]
then
    trim_setting="trim-paired"
    front_option="p-front-f"
    rev_option="p-front-r"
else
    trim_setting="trim-single"
    front_option="p-front"
    rev_option="p-anywhere"
fi

cmd="qiime cutadapt $trim_setting \
    --i-demultiplexed-sequences $demux_artifact \
    --$front_option $FWD_PRIMER \
    --$rev_option $REV_PRIMER \
    --p-error-rate 0.1 \
    --p-indels True \
    --p-times 2 \
    --p-overlap 3 \
    --p-match-read-wildcards True \
    --p-match-adapter-wildcards True \
    --p-minimum-length 50 \
    --p-cores $(nproc) \
    --verbose \
    --o-trimmed-sequences $trim_output"
echo $cmd
echo
eval $cmd
echo

### 3) Join reads
if [ $PAIRED == "true" ]
then
    echo MERGING PAIRED READS
    join_output=$OUTPUTDIR/joined.qza
    cmd="qiime vsearch join-pairs \
    --i-demultiplexed-seqs $trim_output \
    --p-maxdiffs 200 \
    --p-maxee 20 \
    --p-minovlen 1 \
    --p-allowmergestagger True \
    --verbose \
    --o-joined-sequences $join_output"
    echo $cmd
    eval $cmd
fi